//! Constants used by the Win32 debug loop. Kept in its own module so
//! that the main `backend.rs` doesn't have to repeat the bit-fiddling.

use windows::Win32::Foundation::NTSTATUS;
use windows::Win32::System::Diagnostics::Debug::DEBUG_EVENT_CODE;

pub const DBG_CONTINUE: NTSTATUS = NTSTATUS(0x0001_0002u32 as i32);
pub const DBG_EXCEPTION_NOT_HANDLED: NTSTATUS = NTSTATUS(0x8001_0001u32 as i32);

pub const EXCEPTION_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(1);
pub const CREATE_THREAD_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(2);
pub const CREATE_PROCESS_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(3);
pub const EXIT_THREAD_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(4);
pub const EXIT_PROCESS_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(5);
pub const LOAD_DLL_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(6);
pub const UNLOAD_DLL_DEBUG_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(7);
pub const OUTPUT_DEBUG_STRING_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(8);
pub const RIP_EVENT_C: DEBUG_EVENT_CODE = DEBUG_EVENT_CODE(9);

pub const EXC_BREAKPOINT: i32 = 0x8000_0003u32 as i32;
pub const EXC_SINGLE_STEP: i32 = 0x8000_0004u32 as i32;
pub const EXC_ACCESS_VIOLATION: i32 = 0xC000_0005u32 as i32;
pub const EXC_ILLEGAL_INSTRUCTION: i32 = 0xC000_001Du32 as i32;
pub const EXC_INT_DIVIDE_BY_ZERO: i32 = 0xC000_0094u32 as i32;
